"""empty message

Revision ID: eaeaad495ec7
Revises: 1e473a0afbd2
Create Date: 2023-07-14 09:44:01.180225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaeaad495ec7'
down_revision = '1e473a0afbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.String(length=250), nullable=True))
        batch_op.drop_column('terrin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrin', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('terrain')

    # ### end Alembic commands ###
